name: 🐞 Pull request
description: Create a pull request to help us improve
title: "[PR] "
labels: ["PR"]

body:
- type: markdown
  attributes:
    value: |
      Thank you for reporting a bug! Please fill out the form below with as much detail as possible.

- type: textarea
  id: bug_description
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
    placeholder: Describe the bug...
  validations:
    required: true

- type: textarea
  id: to_reproduce
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. Scroll down to '...'
      4. See error
  validations:
    required: true