name: Run test script

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    env:
      SHOULD_SIGN: ${{ startsWith(github.ref, 'refs/tags/') }}
      EVENT_CONTEXT: ${{ toJSON(github.event) }}

    steps:
    
    - name: Output event context
      run: |
        echo $EVENT_CONTEXT

    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Print all environment variables
      shell: pwsh
      run: |
        Get-ChildItem Env:
    
    - name: Should sign? - true
      if: ${{ env.SHOULD_SIGN == 'true' }}
      run: |
        echo 'Signing'
    
    - name: Should sign? - false
      if: ${{ env.SHOULD_SIGN == 'false' }}
      run: |
        echo 'Not signing'